# Generated by Django 4.2.7 on 2023-11-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('pump_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pump_name', models.CharField(max_length=30, unique=True)),
                ('pump_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
