# Generated by Django 4.2.7 on 2023-11-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chassis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='chassis_cost',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
