# Generated by Django 4.2.7 on 2023-11-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type_code', models.CharField(max_length=2)),
                ('user_type_name', models.CharField(max_length=50)),
            ],
        ),
    ]
