# Generated by Django 4.2.7 on 2023-11-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindetail',
            name='name',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='admindetail',
            name='password',
            field=models.CharField(default='test', max_length=30),
        ),
        migrations.AddField(
            model_name='admindetail',
            name='user_type_code',
            field=models.CharField(default='AD', max_length=2),
        ),
        migrations.AddField(
            model_name='admindetail',
            name='username',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='name',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='password',
            field=models.CharField(default='test', max_length=30),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='user_type_code',
            field=models.CharField(default='CT', max_length=2),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='username',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='supplierdetail',
            name='name',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='supplierdetail',
            name='password',
            field=models.CharField(default='test', max_length=30),
        ),
        migrations.AddField(
            model_name='supplierdetail',
            name='user_type_code',
            field=models.CharField(default='SU', max_length=2),
        ),
        migrations.AddField(
            model_name='supplierdetail',
            name='username',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
