# Generated by Django 4.2.7 on 2023-11-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('engine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('engine_name', models.CharField(max_length=40, unique=True)),
                ('horsepower', models.IntegerField()),
                ('peak_torque', models.IntegerField()),
                ('dry_weight', models.IntegerField()),
                ('cylinders', models.IntegerField()),
                ('displacement', models.IntegerField()),
                ('clutch_engagement_torque', models.IntegerField()),
                ('governed_speed', models.IntegerField()),
                ('engine_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
