# Generated by Django 4.2.7 on 2023-11-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aerial_id', models.IntegerField()),
                ('class_id', models.IntegerField()),
                ('aerial_name', models.CharField(max_length=60)),
                ('basket', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hstyle_jack', models.IntegerField()),
                ('downjack', models.IntegerField()),
                ('stabilizer_spread', models.FloatField()),
                ('structural_ladder_warranty', models.IntegerField()),
                ('flow_capacity', models.IntegerField()),
                ('minimum_angle', models.FloatField()),
                ('maximum_angle', models.FloatField()),
                ('wind_rating', models.FloatField()),
                ('ice_rating', models.FloatField()),
                ('horizontal_ladder_reach', models.FloatField()),
                ('vertical_ladder_reach', models.FloatField()),
                ('dry_payload_capacity', models.IntegerField()),
                ('wet_payload_capacity', models.IntegerField()),
                ('tank', models.IntegerField()),
                ('aerial_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
